== Summary

This Health Spatial Data Infrastructure white paper provides a discussion about the collection, exchange, integration, analysis, and visualization of health and non-health data to support health applications. Applications that address health issues at global and population level scale as well as at the local, individual patient scale. This paper identifies opportunities to advance OGC Standards towards building a framework to support Health Spatial Data Infrastructures (SDIs).

Developing a Health SDI based on open standards will help health data users and other stakeholders in the following ways:

* *Solution Providers* - to understand market needs and add value to services;
* *Market Participants* - to understand where OGC standards can be applied to support improved health outcomes;
* *Government and Institutes* - to understand market priorities surrounding the need and use of data in healthcare, and to design health-oriented SDIs;
* *Standards Organizations* - to understand opportunities to develop or improve standards to support health applications and the healthcare industry overall;
* *Researchers* - to have a foundation of elements for advancing research on SDIs and health-related applications using OGC Standards;
* *Health and Medical Researchers* - to understand how geospatial analytics on health and social data sets can causes and consequences of poor health outcomes that may be in need to further research towards identifying viable treatment options, as well as advancing the research towards solutions to population health challenges;
* *Health Systems* - to understand how such a framework could contribute to clinician point-of-care decision support and be leveraged to improve patient care and overall population health;
* *Insurers* - to understand how geospatial analytics on health and social data sets can indicate long-term health risks of populations, as well as potential means of intervening on those risks.

The paper builds on contributions from OGC Health DWG members and is informed by OGC Health DWG sessions from 2012-2019, including Summits in 2016 and 2017. The following key application areas are addressed providing a broad scope of market requirements and functional areas:

* Climate-Health
* Healthy Aging
* Health in the Smart City
* Disaster Resilience
* Global Indicators

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Luis Bermudez | OGC
|Eddie Oldfield | Spatial Quest
|Scott Serich | OGC
|Ajay K Gupta | HSR.health
|====================


// *****************************************************************************
// please don't change the foreword
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
