== Summary

This Health Spatial Data Infrastructure white paper provides a discussion about the collection, exchange, integration, analysis, and visualization of health and non-health data to support health applications. Applications that address health issues at global and population level scale as well as at the local, individual patient scale are presented. This paper identifies opportunities to advance OGC Standards towards building a framework to support Health Spatial Data Infrastructures (SDIs).

Developing a Health SDI based on open standards will help health data users and other stakeholders in the following ways:

* *Solution Providers* - to understand market needs and add value to services;
* *Market Participants* - to understand where OGC standards can be applied to support improved health outcomes;
* *Government and Institutes* - to understand market priorities surrounding the need and use of data in healthcare, and to design health-oriented SDIs;
* *Standards Organizations* - to understand opportunities to develop or improve standards to support health applications and the healthcare industry overall;
* *Researchers* - to have a foundation of elements for advancing research on SDIs and health-related applications using OGC Standards;
* *Health and Medical Researchers* - to understand how geospatial analytics on health and social data sets can causes and consequences of poor health outcomes that may be in need to further research towards identifying viable treatment options, as well as advancing the research towards solutions to population health challenges;
* *Health Systems* - to understand how such a framework could contribute to clinician point-of-care decision support and be leveraged to improve patient care and overall population health;
* *Insurers* - to understand how geospatial analytics on health and social data sets can indicate long-term health risks of populations, as well as potential means of intervening on those risks.

More generally, Health SDIs must become a mainstream component of the world’s healthcare infrastructure not only because of the critical and central role that health - and good health - plays in human life, but also because it is the most expensive thing that most countries spend their resources on. It is well known that the U.S. health systems is unsustainable at 20% of its GDP, but the growth rate in healthcare expenses is also unsustainable in other countries at 11% of their GDP. 

The need to idenfity solutions to reduce the cost of healthcare - in developed nations and elsewhere - is important. It may also be important to realize that the solutions to reduce the cost of healthcare may not be coming from within healthcare. This is because advances in healthcare are always more expensive than any medical technology, treatments, or pharmaceutical drugs they replace. Cost control in healthcare may have to come from an information technology solution not only for the potential system-wide efficiencies such technology may be able to create, but also because its ability to integrate health data with non-health and novel data sets allowing for quick diagnosis and identification of revolutionary new population health measures that identify cost drivers as well as their solutions.  

A Health SDI as a platform for analyzing geocoded health data with social data and environmental data and potentially new data sets not yet created is a natural fit, as this document will demonstrate. 

== Key Applications Areas

The paper builds on contributions from OGC Health DWG members and is informed by OGC Health DWG sessions from 2012-2019, including Summits in 2016 and 2017. The following key application areas are addressed providing a broad scope of market requirements and functional areas:

* Climate-Health
* Healthy Aging
* Health in the Smart City
* Disaster Resilience
* Global Indicators

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Luis Bermudez | OGC
|Eddie Oldfield | Spatial Quest
|Scott Serich | OGC
|Ajay K Gupta | HSR.health
|====================


// *****************************************************************************
// please don't change the foreword
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
