== Summary

This Health Spatial Information Framework white paper provides a discussion about the exchange, integration, analysis, and visualization of health and non-health data to support health applications. It identifies opportunities to advance the OGC Standards towards building a framework to support Health Spatial Data Infrastructures (SDIs).

Developing a Health Spatial Information Framework based on open standards will help health data users and other stakeholders in the following ways:

* *Solution Providers* - to understand market needs and add value to services;
* *Market Participants* - to understand where OGC standards can be applied to support improved health outcomes;
* *Government and Institutes* - to understand market priorities and to design health-oriented SDIs;
* *Standard Organizations* - to understand opportunities to develop or improve standards to support health applications;
* *Researchers* - to have a foundation of elements for advancing research on SDIs and health-related applications using OGC Standards.

The paper builds on contributions from OGC Health DWG members and is informed by OGC Health DWG sessions from 2012-2017, including Summits in 2016 and 2017. Four key application areas are addressed, providing a broad scope of market requirements and functional areas:

* Climate-Health
* Healthy Aging
* Global Indicators
* Health in the Smart City

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Luis Bermudez | OGC
|Eddie Oldfield | Spatial Quest
|Scott Serich | OGC
|====================


// *****************************************************************************
// please don't change the foreword
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
