[[Introduction]]
== Introduction

One hundred and fifty years ago, John Snow demonstrated the value of spatial relationships by combining cholera death and water pump locations to predict the development of infectious disease outbreaks. Today, GIS, computing, modeling, statistics, sensors, geospatial data and OGC web service standards are enabling powerful spatial analysis to support health and epidemiological research. However there is not a documented framework that provides an architecture and interfaces to support a health spatial data infrastructure.

Discussions around the framework has been advanced by the OGC Health Domain Working Group (Health DWG). This DWG convened a  http://external.opengeospatial.org/twiki_public/HealthDWG/WebHome[Health Summit], during the OGC TC in Dublin in June 2016. Through interviews and discussion, participants indicated that a future state of a Spatial Data Infrastructure would include implementation of more widely accepted interoperability (OGC) standards-based technologies and services, improved privacy and security best practices, and common vocabularies.

Ideas from participants on the climate-health panel coalesced around the need to improve interoperability of geospatial data and web services to facilitate more sophisticated climate-health applications. Ideas from the healthy-aging panel coalesced around the ability of sensor networks to support active and healthy aging, connecting indoor sensors and devices to support clinical records and the wellbeing of patients with cognitive impairments (as an example) - this culminated in the creation of an Active and Healthy Aging Observation and Measurement (AHA O&M) Profile. Ideas from participants on the healthy urban environments panel coalesced around the need for well-defined protocols for using health information in mapping applications while protecting privacy, to better understand interaction between disease and health determinants (including built environment).

Since the Health Summit in 2016, interest continues to be expressed in the potential for OGC standards to support health domain requirements, helping to solve interoperability challenges for integrating health data with non-health data (e.g. environmental determinants of health). But disparities remain in the adoption of standards and frameworks to collect, process, store, integrate, visualize, and protect information, especially with complex Big Data scenarios. Health professionals rarely have access to or are not able to use climate and weather data for diagnosing, treating, monitoring, or advising a patient; or to take informed action based on environment and health data mashups, or to determine causal relationships over various spatial and temporal scales. The data challenge includes several aspects: quantity of data, distributed nature of data, the heterogeneity and diversity of the data, the lack of data sharing due to both policy and technology limitations, and difficulties to share across disciplines, organizations, and geographic boundaries.

Furthermore it is important to look at how geospatial standards are used to support indicators on a spatiotemporal basis to help determine current state and plan for action related to  global disparities for health impacts from disasters and climate change. Challenges still remain on spatiotemporal understanding of health impacts (e.g. injury, illness, death) from climate change and environmental health determinants, population vulnerabilities and adaptive capacity, and other possible complex exposures (diets, lifestyles, etc).

This white paper, as well as potential future activities to advance the framework, will continue to be discussed at future Health DWG meetings and summits.

This paper first presents and introduction and background, then discusses key application areas, and finally proposes a framework to support Health SDIs. The resulting framework will serve as the basis for agencies around the globe to support regional SDIs and to develop prototype activities under the OGC Innovation Program for further refinement of framework capabilities.
