[[Introduction]]
== Introduction

One hundred and fifty years ago, Dr. John Snow demonstrated the value of spatial relationships by combining the locations of cholera deaths and water pumps to track the progress of an outbreak of this infectious disease back to its source. Today, geographic information systems (GIS), computing, modeling, statistics, sensors, geospatial data and OGC web service standards are enabling powerful spatial analysis to support health and epidemiological research. However, there is not a documented framework that provides an architecture and interfaces to support a health spatial data infrastructure.

Discussions around the framework has been advanced by the OGC Health Domain Working Group (Health DWG). This DWG convened a Health Summit, during the OGC Technical Committee (TC) meeting in Dublin, Ireland in June 2016. Through interviews and discussion, participants indicated that a future state of a Spatial Data Infrastructure (SDI) would include implementation of more widely accepted interoperable standards-based technologies and services, improved privacy and security best practices, and common vocabularies.

Ideas from participants on the climate-health panel coalesced around the need to improve interoperability of geospatial data and web services to facilitate more sophisticated climate-health applications. Ideas from the healthy-aging panel coalesced around the ability of sensor networks to support active and healthy aging, connecting indoor sensors and devices to support clinical records and the wellbeing of patients with cognitive impairments (as an example) – this culminated in the creation of an Active and Healthy Aging Observation and Measurement (AHA O&M) Profile. Ideas from participants on the healthy urban environments panel coalesced around the need for well-defined protocols for using health information in mapping applications while protecting privacy, to better understand interaction between disease and health determinants, including social and environmental factors. 

Since the Health Summit in 2016, interest continues to be expressed in the potential for OGC standards to support health domain requirements, helping to solve interoperability challenges for integrating health data with non-health data (commonly called social determinants of health or SDoH). But disparities remain in the adoption of standards and frameworks to collect, process, store, integrate, analyze, visualize, share, and protect information, especially within complex Big Data scenarios. Health professionals rarely or at best inconsistently have access to or are able to use, for example, climate and weather data for diagnosing, treating, monitoring, or advising a patient; or to take informed action based on environment and health data mashups, or to determine causal relationships over various spatial and temporal scales. 

While it is recognized by the medical community that the environmental factors these data sources represent can impact health outcomes for a wide range of patient conditions (e.g., asthma, allergies, depression, isolation, stress, skin conditions, etc.), these data sources are not available with the same consistency and accuracy of other health data (e.g., lab results and patient vital signs). This complicates provider efforts to leverage this data to take informed action and to determine causal relationships over various spatial and temporal scales.

The data challenge includes several aspects: quantity of data, consistency of data availability, ability to customize data to meet diverse provider requirements, distributed nature of data, the heterogeneity and diversity of the data, the lack of data sharing due to both policy and technology limitations, and difficulties to share across disciplines, organizations, and geographic boundaries. The timeliness of the data is also a potential challenge. Healthcare Data must be available at the point-of-care and while care is being delivered. Data and information provided to the treating clinicians after treatment has been given is of much less utility. Data and information must also be synthesized into a directly actionable format – and provided within the clinical team’s current workflow and processes. 

Healthcare is a time-sensitive industry, data and data flows must accommodate those realities in order to be effective.  

Furthermore, it is important to look at how geospatial standards are used to support indicators on a spatiotemporal basis to help determine current state and plan for action related to global disparities for health impacts from disasters and climate change. Challenges still remain on spatiotemporal understanding of health impacts (e.g. injury, illness, death) from climate change and environmental health determinants, population vulnerabilities and adaptive capacity, and other possible complex exposures (diets, lifestyles, etc.).

It is also worth noting that sometimes making more information available to the public can have unexpected collateral consequences. For example, identifying cities or neighborhoods with heightened risk to asthma patients could potentially cause real estate valuations in the area to fall.

This white paper, as well as potential future activities to advance the framework towards a Health SDI, will continue to be discussed at future Health DWG meetings and summits.

This paper first presents an introduction and background, then discusses key application areas, and finally proposes a framework to support Health SDIs. The resulting framework will serve as the basis for agencies around the globe to support regional SDIs and to develop prototype activities under the OGC Innovation Program for further refinement of framework capabilities.

There is also not a defined framework for how to use geospatial data analytics to derive potential solutions to population health challenges. That is a missing link towards which this white paper hopes to serve as a first step.

