[[Introduction]]
== Introduction 

One hundred and fifty years ago, John Snow demonstrated the value of spatial relationships, by combining cholera death and water pump locations to predict the development of infectious disease outbreaks.  Today, GIS, computing, modelling, statistics, sensors, geospatial data and OGC web service standards, are enabling  powerful spatial analysis to support health and epidemiological research.  However there is not a documented framework that provides an architecture and  interfaces to support a health spatial data infrastructure.

Discussions around the framework has been advanced by  the OGC Health Domain Working Group (Health DWG). A group convened a  http://external.opengeospatial.org/twiki_public/HealthDWG/WebHome[Health Summit in Dublin], during the OGC TC in June  2016. Through interviews and discussion, participants indicated that a future state of a Spatial Data Infrastructure would include:  implementation of  wider-accepted interoperable (OGC) standard based technologies and services, improved privacy and security best practices, and common vocabularies.

Participants on the climate-health panel coalesced around the need to improve interoperability of geospatial data and web services to facilitate more sophisticated climate-health applications. Participants in the healthy-ageing panel coalesced around the ability of sensor networks to support active and healthy ageing, connecting indoor sensors and devices to support clinical records and the wellbeing of patients with cognitive impairments (as an example) - this culminated in the creation of an Active and Healthy Ageing Observation and Measurement (AHA O&M) Profile.  Participants in the healthy urban environments panel coalesced around the need for well-defined protocols for using health information in mapping applications while protecting privacy, to better understand interaction between disease and health determinants (including built environment). 

Since the Summit in 2016, interest continues to be expressed in the potential for OGC standards to support health domain requirements, helping to solve interoperability challenges for integrating health data with non-health data (e.g. environmental determinants of health), but disparities remain in the adoption of standards and frameworks to collect, process, store, integrate, visualize, and protect information, especially with complex Big Data scenarios.  Health professionals rarely have access to or are not able to use climate and weather data for diagnosing, treating, monitoring, or advising a patient; or to take informed action based on environment and health data mashups, or to determine causal relationships over various spatial and temporal scales. The data challenge includes several aspects: quantity of data, distributed nature of data, the heterogeneity and diversity of the data, the lack of data sharing due to both policy and technology limitations, and difficulties to share across disciplines, organisations, and geographic boundaries. 

Furthermore it is important to look at how geospatial standards are used to support indicators on a spatio-temporal basis to help determine current state and plan for action related to  global disparities for health impacts from disasters and climate change.   Challenges still remain on spatial-temporal understanding of health impacts (e.g. injury, illness, death) from  climate change and environmental health determinants, population vulnerabilities and adaptive capacity, and other possible complex exposures (diets, lifestyles, etc).  

A second health summit is to take place at the OGC TC meeting in St, Jones in June 2017. At this meeting this white paper will be discussed as well as potential future activities to advance the framework.

This white paper first presents background activities, then discusses key application areas and finally it proposes a framework to support a Health Spatial Data Infrastructures. The resulting framework will serve as the basis for agencies around the globe to support regional spatial data infrastructures, as well as for developing prototype activities under the OGC Innovation Program for further refinement of the system.


