[[Introduction]]
== Application Areas

Development of a Health SDI requires understanding of the use cases that the SDI should support. The following use cases are included in this document:

* Climate Health
* Healthy Aging
* Health in the Smart City
* Disaster Resilience 
* Global Indicators
* Maternal Mortality

== Climate Health

Climate variability can pose significant threats to human health and well-being in the form of higher temperatures, increased extreme weather events, such as hurricanes and wildfires, decreased air quality, water shortages, and illnesses transmitted by food, water, and disease carriers such as mosquitoes and ticks. Extreme storms and temperatures can also disrupt the delivery of health services by causing damage to roads and transportation infrastructure, hospitals, clinics, wastewater treatment plants, and other facilities. Climate variability can also impact economic sectors that support health, such as energy, transportation, and agriculture. 

As a case in point, there are many individuals in the U.S. who depend on electrically powered, life-saving medical devices, such as ventilators, cardiac devices, and home dialysis machines. These individuals depend on the medical devices to function properly, and therefore also depend on available and continuous electrical power. The U.S. Department of Health and Human Services (HHS) produces an https://empowermap.hhs.gov/[emPOWER map] (shown in Figure 2) that provides a visualization by region (state, county, or ZIP Code level) as well as the specific number of people in tabular form of those who depend on such devices. For instance, the U.S. state of Georgia is home to 77,930 such individuals.

ADD FIGURE 2

A Health SDI could help in the development of new ways to monitor, prevent, and respond to climate impacts on human health. Steps taken to prepare for climate impacts can improve health and provide other societal benefits, such as sustainable development, disaster risk reduction, and improvements in quality of life.

Applications arising from a Health SDI could help health authorities publish up-to-date maps showing various dimensions of disease, population health, and environment. Economies of scale can be leveraged when epidemiological research and health planning communities utilize a coordinated system to address inequalities in and stresses on health systems and healthcare provision, access, and promotion. Applications can be scaled up to support more sophisticated climate-health scenarios, particularly during health emergencies and for pandemic response efforts.

Research collaboratives such as the http://lancetcountdown.org/[Lancet Countdown] can also inform framework development. The Lancet Countdown tracks the world’s response to climate change and health benefits that may emerge from this response. This reporting is done annually, and different indicators are evaluated and changed as needed. The Countdown proposes five thematic breakdowns:

*	Climate change impacts, exposures and vulnerability;
*	Adaption planning and resilience for health;
*	mitigation action and health co-benefits;
*	Economics and finance; and
*	Political and broader engagement.

These thematic breakdowns, along with associated indicator domains, could be used to provide organizing principles for a health SDI or perhaps even for the overall spatial information framework itself. There were 40 indicators in 2017. In 2018, a https://sciencepolicy.colorado.edu/admin/publication_files/2018.14.pdf[revision of the indicators] led to the inclusion of a new indicator under the Public and Political Engagement breakdown called Corporate Sector Engagement in Health and Climate Change. The list of indicators from 2017 and 2018 appear in the Appendix.

===Paris Agreement on Climate Change

The https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement[Paris Agreement on Climate Change] was held in December 2015, at the http://www.cop21paris.org/[2015 UN Climate Change Conference (CoP21)], held in Paris, France. It highlighted that mitigating Green House Gas (GHG) emissions and air pollution can reduce health impacts and costs. There will be a global assessment every 5 years to assess the collective progress toward achieving the purpose of the agreement and the inform other parties of individual actions.

== Health Aging

Some populations are more vulnerable than others to changes in health status. Vulnerable populations of concern include children, pregnant women, those with low income, immigrant groups, indigenous peoples, communities of color, as well as older adults. It is well known that the bulk of the healthcare expenditure goes towards care for senior populations. In the U.S., 36% of healthcare spending is attributed to the 65 and over population, even though they make up only 16% of the U.S. population.   

In order to address and reduce the vulnerability of aging populations, health organizations are increasingly turning to geospatial analysis to assess and prioritize areas for intervention based on location.

===Geospatial Tech to Address Costs

Geospatial tools linking social determinants of health (SDoH) with health conditions, outcomes, and costs associated with the elderly can identify those social factors that are root causes of or influencers of poor health outcomes, and their associated high costs. Identifying root causes of poor health outcomes of the elderly populations will allow health systems, working within their communities, to address the underlying social factors and achieve improved health and quality of life for those communities. 

===Mobility and Ease of Access

Mobility and simply “getting around” are often reported as challenges for the elderly population. Limited mobility often leads to isolation, which in turn can cause and exacerbate many health conditions. Geospatial technology can address mobility issues in part by assessing and rating parks, public areas, and internal building structures on ease of mobility, such as the presence or absence of elevators, hand-rails on stairwells, ramps in place of steps for short elevations, as well as other health-related issues such as mold, temperature, air quality, etc. 

Geospatial technology can also identify gradations in topology and elevation in public parks or city-wide areas to provide information on walking tracks. 
