[[Introduction]]
=== Climate-Health

Climate variability can pose significant threats to human health and well-being in the form of higher temperatures, increased extreme weather events, wildfire, decreased air quality, and illnesses transmitted by food, water, and disease carriers such as mosquitoes and ticks. Extreme storms and temperatures can also disrupt the delivery of health services and damage hospitals, clinics, wastewater treatment plants, and other facilities. Climate variability can also impact economic sectors that support health, such as energy, transportation, and agriculture. A Health Spatial Information Framework could help in the development of new ways to monitor, prevent, and respond to climate impacts on human health. Steps taken to prepare for climate impacts can improve health and provide other societal benefits, such as sustainable development, disaster risk reduction, and improvements in quality of life.

Applications arising from a Health Spatial Information Framework could help health authorities publish up-to-date maps showing various dimensions of disease, population health, and environment. Economies of scale can be leveraged when epidemiological research and health planning communities utilize a coordinated system to address inequalities in health care provision, access, and promotion. Applications can be scaled up to support more sophisticated climate-health scenarios, particularly during health emergencies and for pandemic response efforts (cite:[RN752, RN753]).

Research collaboratives such as the http://lancetcountdown.org/[Lancet Countdown] (cite:[RN768]) could also inform framework development. The Countdown proposed five thematic working groups:

* Health impacts of climate hazards;
* Health resilience and adaptation;
* Health co-benefits of climate change mitigation;
* Economics and finance; and
* Political and broader engagement.

These working groups, along with associated indicator domains, could be used to provide organizing principles for a health spatial data infrastructure or perhaps even for the overall spatial information framework itself.

*Paris Agreement on Climate Change*

The Paris Agreement on Climate Change (cite:[RN758]) was held in December 2015, at the Paris Climate Conference (CoP21) by 195 countries. It highlighted that Mitigating Green House Gas (GHG) emissions and air pollution can reduce health impacts and costs.
