[[Introduction]]
=== Climate-Health

Climate variability and related impacts pose significant threats to human health and well-being. These climate impacts come from higher temperatures, increased extreme weather events, wildfire, decreased air quality, threats to mental health, and illnesses transmitted by food, water, and disease carriers such as mosquitoes and ticks.  Extreme storms and temperatures can disrupt the delivery of health services and damage hospitals, clinics, wastewater treatment plants, and other facilities. Climate also impacts economic sectors that support health, such as energy, transportation, and agriculture.  Health organizations are increasingly interested to develop ways to monitor, prevent, and respond to climate impacts on human health.  Steps taken to prepare for climate impacts can improve health and provide other societal benefits, such as sustainable development, disaster risk reduction, and improvements in quality of life.

Relying on a  Health Spatial Information Framework , health authorities could publish up-to-date maps showing various dimensions of disease, population health, environment, and statistics. The economy of scale is present when epidemiological research and health planning communities utilize a system to address inequalities in health care provision, access, and promotion, which can be scaled up for sophisticated climate-health scenarios, during health emergencies and for pandemic response efforts cite:[RN752, RN753].