=== Global Indicators
Various global initiatives have provided guidance towards global indicators to help monitor the status of health in populations. The initiatives include Sustainable Development Goal developed by the United Nations, the Sendai Framework for Disaster Risk Reduction and the Paris Agreement on Climate Change.

*United Nations Sustainable Development Summit - Sustainable Development Goals*

At the United Nations Sustainable Development Summit 2015, 193 countries agreed on the Sustainable Development Goals (SDGs). For each goal specific objectives and targets were defined (cite:[RN755]). The goal related to health is _Goal 3  Good Health and Wellbeing_. The objective of this goal is to "Ensure healthy lives and promote well-being for all at all ages". Thirteen targets and associated indicators were developed by the Interagency and Expert Group on SDG Indicators (IAEG-SDGs).

*Indicators for the Sustainable Development Goal 3 **Good Health and Wellbeing*

[source]
--
   3.1.1 Maternal mortality ratio
   3.1.2 Proportion of births attended by skilled health personnel
   3.2.1 Under-five mortality rate
   3.2.2 Neonatal mortality rate
   3.3.1 Number of new HIV infections per 1,000 uninfected population, by sex, age and key populations
   3.3.2 Tuberculosis incidence per 100,000 population
   3.3.3 Malaria incidence per 1,000 population
   3.3.4 Hepatitis B incidence per 100,000 population
   3.3.5 Number of people requiring interventions against neglected tropical diseases
   3.4.1 Mortality rate attributed to cardiovascular disease, cancer, diabetes or chronic respiratory disease
   3.4.2 Suicide mortality rate
   3.5.1 Coverage of treatment interventions (pharmacological, psychosocial and rehabilitation and aftercare services) for substance use disorders
   3.5.2 Harmful use of alcohol, defined according to the national context as alcohol per capita consumption (aged 15 years and older) within a calendar year in litres of pure alcohol
   3.6.1 Death rate due to road traffic injuries
   3.7.1 Proportion of women of reproductive age (aged 15-49 years) who have their need for family planning satisfied with modern methods
   3.7.2 Adolescent birth rate (aged 10-14 years; aged 15-19 years) per 1,000 women in that age group
   3.8.1 Coverage of essential health services (defined as the average coverage of essential services based on tracer interventions that include reproductive, maternal, newborn and child health, infectious diseases, non-communicable diseases and service capacity and access, among the general and the most disadvantaged population)
   3.8.2 Proportion of population with large household expenditures on health as a share of total household expenditure or income
   3.9.1 Mortality rate attributed to household and ambient air pollution
   3.9.2 Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (exposure to unsafe Water, Sanitation and Hygiene for All (WASH) services)
   3.9.3 Mortality rate attributed to unintentional poisoning
   3.a.1 Age-standardized prevalence of current tobacco use among persons aged 15 years and older
   3.b.1 Proportion of the target population covered by all vaccines included in their national programme
   3.b.2 Total net official development assistance to medical research and basic health sectors
   3.b.3 Proportion of health facilities that have a core set of relevant essential medicines available and affordable on a sustainable basis
   3.c.1 Health worker density and distribution
   3.d.1 International Health Regulations (IHR) capacity and health emergency preparedness
--

There are other health related goals and indicators related to poverty, education, food / nutrition (malnutrition), food supply, water / vector borne disease, mental health, and occupational health and safety.

Each country will be able to measure progress toward achieving the objectives using the indicators. Health indicators at the national and sub-national level consist of data obtained by national health agencies, statistical agencies e.g. census data, and regional health authorities. Lack of availability at the local and regional levels, constraining ability to measure indicators for all regions. There are also challenges for integrating, analyzing, and visualizing indicator data at a sub-national level (at various scales) by countries adopting the indicators due to  inconsistencies in data collection.

*Sendai Framework for Disaster Risk Reduction*

The UN General Assembly Resolution A/RES/71/276 (cite:[RN756]) endorsed the recommendations of the Open-ended intergovernmental expert Working Group on 2 February 2017. The report recommends indicators for the seven global targets of the Sendai Framework for Disaster Risk Reduction 2015-2030 (cite:[RN757]. The indicators related to health are as follows:

_Sendai Framework Indicators Related to Health_
[source]
--
- Global target A: Substantially reduce global disaster mortality by 2030, aiming to lower average per 100,000 global mortality between 2020-2030 compared with 2005-2015.
   - A-1 (compound) Number of deaths and missing persons attributed to disasters, per 100,000 population.
   - A-2 Number of deaths attributed to disasters, per 100,000 population.

- Global target B: Substantially reduce the number of affected people globally by 2030, aiming to lower the average global figure per 100,000 between 2020-2030 compared with 2005-2015.
   - B-2 Number of injured or ill people attributed to disasters, per 100,000 population.
   - B-3 Number of people whose damaged dwellings were attributed to disasters.
   - B-4 Number of people whose destroyed dwellings were attributed to disasters.
   - B-5 Number of people whose livelihoods were disrupted or destroyed, attributed to disasters.

- Global target D: Substantially reduce disaster damage to critical infrastructure and disruption of basic services, among them health and educational facilities, including through developing their resilience by 2030.
   - D-2 Number of destroyed or damaged health facilities attributed to disasters.
   - D-7 Number of disruptions to health services attributed to disasters
--

However, the quality of these indicators is constrained by the quality of the data used to generate them (cite:[RN767]). When high-quality data is accessible, differences in recording can frustrate attempts at aggregation, and even when aggregation is possible, significant subgroup trends can sometimes be masked. As the authors note, the  World Health Organization (WHO) Global Reference List of 100 Core Health Indicators is a step toward alignment in reporting.

The Framework and any supporting OGC Innovation Program activities should take advantage of the momentum established by these 100 indicators.

*Paris Agreement on Climate Change*

The Paris Agreement on Climate Change (cite:[RN758]) was held in December 2015, at the Paris Climate Conference (CoP21) by 195 countries. It highlighted that Mitigating Green House Gas (GHG) emissions and air pollution can reduce health impacts and costs.
