[[Introduction]]
=== Health in the Smart City

Urban residents make up 54% of the global population, and that percentage is growing rapidly impacting environmental sustainability, public services, economic growth and social resilience. Effective integration of human, physical, and digital systems will enable cities to be more prosperous,  sustainable and resilient (cite:[RN764]. 

The  World Health Organization (WHO) Healthy Cities project bring together hundreds of cities under its network to make health a priority on economic, social and political agendas. Boulus (cite:[RN765]), discussed the importance of Internet of Things (IoT) and geospatial analytics empowering health city decisions. One example is the wireless sensors connected to garbage  bins to monitor trash levels in Barcelona. This not only provides data for optimization of data collection but can help minimize pollution related illnesses. Overflowing waste containers can cause bacteria to grow, pollut air and water sources  causing respiratory diseases, salmonella, and fever among others.

Mobile Health in an information technology field that advance the use of Mobile devices to support health services and information. Information from Mobile Health and Smart Cities can improve healthcare and overall quality of life (cite:[RN766]).